title: ""
description: ""
url: https://wenbrau.github.io/
linkedin_username: wendy-brau
github_username: wenbrau
google_scholar: https://scholar.google.com/citations?user=ogp1p4sAAAAJ&hl=en&oi=ao
theme: minima





plugins:
  - jekyll-feed
  - jekyll-seo-tag



header_pages:
  - index.md
  - projects.md
